apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: europe-west1-docker.pkg.dev/quatreapp/qsh-public/4sh-guestbook:1.0
          env:
            - name: REDIS_ADDR
              value: "redis-master:6379"
            - name: REDIS_PASSWORD
              value: "redispassword"
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
